services :
  postgres :
    container_name: postgres-sql-hb
    image: postgres
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : azed123
      PGDATA : /var/lib/postgresql/data
      POSTGRES_DB : home_buddy
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-hb
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local